// Generate supabase/seed.sql from the bundled seed in src/data.ts.
//
//   node scripts/gen-seed.mjs
//
// Keeps the SQL seed in lock-step with the TypeScript seed so the live DB
// starts life identical to the demo. Uses esbuild (already a Vite dependency)
// to transpile the TS module on the fly.
import { build } from "esbuild";
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// Bundle src/data.ts to a string and import it. The dynamic `import("./lib/supabase")`
// inside hydrate() is never reached here, so we can stub it out to keep the
// bundle self-contained.
const out = await build({
  entryPoints: [resolve(root, "src/data.ts")],
  bundle: true,
  format: "esm",
  write: false,
  platform: "node",
  plugins: [
    {
      name: "stub-supabase",
      setup(b) {
        b.onResolve({ filter: /lib\/supabase$/ }, () => ({ path: "stub", namespace: "stub" }));
        b.onLoad({ filter: /.*/, namespace: "stub" }, () => ({ contents: "export const supabase = null;" }));
      },
    },
  ],
});

const mod = await import("data:text/javascript;base64," + Buffer.from(out.outputFiles[0].text).toString("base64"));
const { SEED_DISHES, SEED_CUISINES, SEED_COLLECTIONS, SEED_TREND, SEED_HERO_IDS } = mod;

const q = (v) => "'" + String(v).replace(/'/g, "''") + "'";
const heroOrder = new Map(SEED_HERO_IDS.map((id, i) => [id, i]));

const lines = [];
lines.push("-- Morsel — seed catalog (generated by scripts/gen-seed.mjs; do not edit by hand).");
lines.push("-- Idempotent: safe to re-run. Loads the DC/DMV starter set.");
lines.push("");
lines.push("begin;");
lines.push("");

// Dishes
lines.push("insert into dishes (id, img, h, name, rest, hood, price, dist, walk, tag, pct, hero, hero_order, saves_week) values");
lines.push(
  SEED_DISHES.map((d) => {
    const isHero = heroOrder.has(d.id);
    return `  (${q(d.id)}, ${q(d.img)}, ${d.h}, ${q(d.name)}, ${q(d.rest)}, ${q(d.hood)}, ${q(d.price)}, ${q(d.dist)}, ${q(d.walk)}, ${q(d.tag)}, ${d.pct}, ${isHero}, ${isHero ? heroOrder.get(d.id) : "null"}, ${SEED_TREND[d.id] ?? 0})`;
  }).join(",\n"),
);
lines.push(
  "on conflict (id) do update set img=excluded.img, h=excluded.h, name=excluded.name, rest=excluded.rest, hood=excluded.hood, price=excluded.price, dist=excluded.dist, walk=excluded.walk, tag=excluded.tag, pct=excluded.pct, hero=excluded.hero, hero_order=excluded.hero_order, saves_week=excluded.saves_week;",
);
lines.push("");

// Reviews — clear then re-insert so re-runs stay clean.
lines.push("delete from reviews;");
const reviewRows = [];
for (const d of SEED_DISHES) {
  d.reviews.forEach((r, i) => reviewRows.push(`  (${q(d.id)}, ${q(r.who)}, ${r.img}, ${q(r.text)}, ${i})`));
}
lines.push("insert into reviews (dish_id, who, img, text, sort) values");
lines.push(reviewRows.join(",\n") + ";");
lines.push("");

// Cuisines
lines.push("insert into cuisines (key, label, img, sort) values");
lines.push(
  SEED_CUISINES.map((c, i) => `  (${q(c.key)}, ${q(c.label)}, ${q(c.img)}, ${i})`).join(",\n"),
);
lines.push("on conflict (key) do update set label=excluded.label, img=excluded.img, sort=excluded.sort;");
lines.push("");

// Collections
lines.push("insert into collections (id, name, sort) values");
lines.push(
  SEED_COLLECTIONS.map((c, i) => `  (${q(c.id)}, ${q(c.name)}, ${i})`).join(",\n"),
);
lines.push("on conflict (id) do update set name=excluded.name, sort=excluded.sort;");
lines.push("");
lines.push("delete from collection_dishes;");
const cdRows = [];
for (const c of SEED_COLLECTIONS) {
  c.dishes.forEach((id, i) => cdRows.push(`  (${q(c.id)}, ${q(id)}, ${i})`));
}
lines.push("insert into collection_dishes (collection_id, dish_id, sort) values");
lines.push(cdRows.join(",\n") + ";");
lines.push("");
lines.push("commit;");
lines.push("");

mkdirSync(resolve(root, "supabase"), { recursive: true });
writeFileSync(resolve(root, "supabase/seed.sql"), lines.join("\n"));
console.log(`Wrote supabase/seed.sql — ${SEED_DISHES.length} dishes, ${reviewRows.length} reviews, ${SEED_CUISINES.length} cuisines, ${SEED_COLLECTIONS.length} collections.`);
